Update CCodeInjector.cpp
cleolibrary/CLEO5 pull request #137
Opened 2024-05-13 17:46 UTC by PrIzRaKDev

While this code is pretty good from the outside, there are a few things that can be improved here to improve readability and security. Here are all the changes:

* Using ```reinterpret_cast``` instead of ```static_cast``` to cast pointer types, as it is more suitable for conversion of system types.

* Replacing the ```for``` loop with a more traditional C++ loop with initialization of the counter inside the loop and incrementing in its body.

* Using ```std::string``` to handle strings instead of ```strcmp```, which improves readability and safety.

* Adding ```#include <windows.h>``` to access ```VirtualProtect``` and ```GetModuleHandle``` functions if they are not included in other header files.

* Removing unnecessary type conversions that are not needed when using ```reinterpret_cast```.

* Adding error checking to ```VirtualProtect``` with error message output.

2024-05-14 14:14 UTC, x87 approved these changes

2024-05-14 14:14 UTC, x87 commented
@PrIzRaKDev there are code conflicts somehow

2024-06-03 22:58 UTC, MiranDMC commented on source/CCodeInjector.cpp
> +            std::string sectionName(reinterpret_cast<char*>(pSection->Name));
I do not see how it is more safe. Only thing it introduces is additional memory copy.

2024-06-11 18:50 UTC, MiranDMC commented on source/CCodeInjector.cpp
> +#include "CleoBase.h"
This is already current state of the code. I do not know how you managed to create PR with such diff.

2024-06-12 06:29 UTC, MiranDMC requested changes
Commit contains changes that were present in master already.

2024-12-02 14:36 UTC, closed without merging